# minimal conda environment
name: aoc
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13
  - pip
  - pip:
    - sqlalchemy==2.0.*
    - pytest
    - alembic
    - numpy
